Description: ECS task and service for Spring Boot Admin

Parameters:

  VPC:
    Type: 'AWS::EC2::VPC::Id'

Resources:

  Task:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: example-spring-boot-admin
      ContainerDefinitions:
      - Name: spring-boot-admin
        Essential: 'true'
        Image: 'amoraes/spring-cloud-ecs-example-spring-boot-admin:latest'
        Memory: 300
        HealthCheck:
          Command: [ 'CMD-SHELL', 'curl -f http://localhost:8080/spring-boot-admin/actuator/health | grep UP || exit 1' ]
          Interval: 10
          Retries: 3
          StartPeriod: 60
          Timeout: 5
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !ImportValue ExampleECSClusterCloudWatchLogGroup
            awslogs-region: !Ref 'AWS::Region'
            awslogs-stream-prefix: 'spring-boot-admin'
        Environment:
        - Name: SPRING_PROFILES_ACTIVE
          Value: 'aws'
        - Name: 'spring.cloud.config.uri'
          Value: !Join ['', [ 'http://', !ImportValue ExampleECSClusterInternalALBDomain, '/config-server' ]]
        - Name: JAVA_OPTIONS
          Value: '-Xmx256m'
        PortMappings:
        - ContainerPort: 8080

  Service:
    Type: AWS::ECS::Service
    DependsOn: ListenerRule
    Properties:
      Cluster: !ImportValue ExampleECSCluster
      DesiredCount: 1
      TaskDefinition: !Ref Task
      HealthCheckGracePeriodSeconds: 30
      LoadBalancers:
      - ContainerName: 'spring-boot-admin'
        ContainerPort: 8080
        TargetGroupArn: !Ref TargetGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      TargetType: instance
      HealthCheckPath: '/spring-boot-admin/actuator/health'
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VPC

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn:
          Ref: TargetGroup
      Conditions:
      - Field: path-pattern
        Values:
        - '/spring-boot-admin*'
      ListenerArn: !ImportValue ExampleECSClusterInternalALBHttpListernArn
      Priority: 30
